FROM rustembedded/cross:x86_64-unknown-linux-musl

COPY openssl.sh /
RUN bash /openssl.sh linux-x86_64 x86_64-linux-musl-

RUN apt install -y llvm-dev libclang-dev clang

ENV OPENSSL_ROOT_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    LCB_NO_PLUGINS=1 \
    LCB_NO_SSL=1
